import Link from "next/link";
import { and, count, desc, eq } from "drizzle-orm";
import { requireUser } from "@/modules/identity/application/authorization";
import { getDatabase } from "@/infrastructure/database/client";
import { collectionItems, collections, creations, favorites, users } from "@/infrastructure/database/schema";
import { COLLECTION_VISIBILITY_MESSAGES, CREATION_TYPE_MESSAGES } from "@/i18n/domain-labels";
import { getServerTranslator } from "@/i18n/server";
import { addToCollection, createCollection, deleteCollection } from "./actions";

export default async function CollectionsPage() {
  const user = await requireUser();
  const { t } = await getServerTranslator();
  const db = getDatabase();
  const [collectionRows, favoriteRows, ownerRows] = await Promise.all([
    db.select({ id: collections.id, title: collections.title, slug: collections.slug, description: collections.description, visibility: collections.visibility, itemCount: count(collectionItems.creationId) }).from(collections).leftJoin(collectionItems, eq(collectionItems.collectionId, collections.id)).where(eq(collections.ownerId, user.id)).groupBy(collections.id).orderBy(desc(collections.updatedAt)),
    db.select({ id: creations.id, slug: creations.slug, title: creations.title, type: creations.type, createdAt: favorites.createdAt }).from(favorites).innerJoin(creations, eq(creations.id, favorites.creationId)).where(and(eq(favorites.userId, user.id), eq(creations.status, "published"))).orderBy(desc(favorites.createdAt)).limit(50),
    db.select({ handle: users.handle }).from(users).where(eq(users.id, user.id)).limit(1),
  ]);
  const ownerHandle = ownerRows[0]?.handle;
  return <><header className="dashboard-header"><div><h1>{t("settings.collections.title")}</h1><p>{t("settings.collections.subtitle")}</p></div></header><div className="dashboard-row"><section className="dashboard-card"><h2>{t("settings.collections.createTitle")}</h2><form className="dashboard-form" action={createCollection}><label>{t("settings.collections.name")}<input name="title" placeholder={t("settings.collections.namePlaceholder")} required /></label><label>{t("settings.collections.description")}<textarea name="description" maxLength={240} /></label><label>{t("settings.collections.visibility")}<select name="visibility" defaultValue="private"><option value="private">{t("visibility.private")}</option><option value="unlisted">{t("visibility.unlisted")}</option><option value="public">{t("visibility.public")}</option></select></label><button>{t("settings.collections.create")}</button></form></section><section className="dashboard-card"><h2>{t("settings.collections.list")}</h2><div className="setting-list">{collectionRows.map((collection) => { let title: React.ReactNode = collection.title; if (ownerHandle && collection.visibility !== "private") title = <Link href={`/collection/${ownerHandle}/${collection.slug}`}>{collection.title}</Link>; return <div className="setting-item" key={collection.id}><div><b>{title}</b><small>{collection.itemCount} {t("settings.collections.works")} · {t(COLLECTION_VISIBILITY_MESSAGES[collection.visibility])}</small></div><form action={deleteCollection}><input type="hidden" name="collectionId" value={collection.id} /><button>{t("common.delete")}</button></form></div>; })}{collectionRows.length === 0 && <p>{t("settings.collections.empty")}</p>}</div></section></div><section className="dashboard-card syndication-section"><h2>{t("settings.collections.recent")}</h2><table className="dashboard-table"><thead><tr><th>{t("settings.collections.creation")}</th><th>{t("settings.collections.type")}</th><th>{t("settings.collections.organize")}</th></tr></thead><tbody>{favoriteRows.map((favorite) => <tr key={favorite.id}><td><Link href={`/creation/${favorite.slug}`}>{favorite.title}</Link></td><td><span className="role-badge">{t(CREATION_TYPE_MESSAGES[favorite.type])}</span></td><td><form className="review-actions" action={addToCollection}><input type="hidden" name="creationId" value={favorite.id} /><select name="collectionId" required><option value="">{t("settings.collections.choose")}</option>{collectionRows.map((collection) => <option key={collection.id} value={collection.id}>{collection.title}</option>)}</select><button>{t("settings.collections.add")}</button></form></td></tr>)}</tbody></table>{favoriteRows.length === 0 && <p>{t("settings.collections.noFavorites")}</p>}</section></>;
}
