import Link from "next/link";
import { desc, eq, sql } from "drizzle-orm";
import { getDatabase } from "@/infrastructure/database/client";
import { deliveryLogs, deliveryTargets, feedSubscriptions, syndicatedItems } from "@/infrastructure/database/schema";
import { DELIVERY_CHANNEL_MESSAGES, FEED_STATUS_MESSAGES } from "@/i18n/domain-labels";
import { getServerTranslator } from "@/i18n/server";
import { createDeliveryTarget, createFeedSubscription, deleteFeedSubscription, pollFeedSubscription, toggleDeliveryTarget, toggleFeedSubscription } from "./actions";

export default async function AdminSyndicationPage() {
  const { locale, t } = await getServerTranslator();
  const db = getDatabase();
  const [feeds, targets, latestItems, failedDeliveries] = await Promise.all([
    db.select({ id: feedSubscriptions.id, title: feedSubscriptions.title, url: feedSubscriptions.url, status: feedSubscriptions.status, lastPolledAt: feedSubscriptions.lastPolledAt, lastSuccessfulAt: feedSubscriptions.lastSuccessfulAt, failureCount: feedSubscriptions.failureCount, lastError: feedSubscriptions.lastError, itemCount: sql<number>`count(${syndicatedItems.id})` }).from(feedSubscriptions).leftJoin(syndicatedItems, eq(syndicatedItems.sourceId, feedSubscriptions.id)).groupBy(feedSubscriptions.id).orderBy(desc(feedSubscriptions.createdAt)),
    db.select().from(deliveryTargets).orderBy(desc(deliveryTargets.createdAt)),
    db.select({ id: syndicatedItems.id, title: syndicatedItems.title, canonicalUrl: syndicatedItems.canonicalUrl, sourceTitle: feedSubscriptions.title, publishedAt: syndicatedItems.publishedAt }).from(syndicatedItems).innerJoin(feedSubscriptions, eq(feedSubscriptions.id, syndicatedItems.sourceId)).orderBy(desc(syndicatedItems.publishedAt)).limit(12),
    db.select({ value: sql<number>`count(*)` }).from(deliveryLogs).where(eq(deliveryLogs.status, "failed")),
  ]);
  let failureTotal = 0;
  if (failedDeliveries[0]) failureTotal = Number(failedDeliveries[0].value);
  const displayTime = (value: Date | null) => {
    if (!value) return t("common.notRun");
    return value.toLocaleString(locale);
  };
  return <>
    <header className="dashboard-header"><div><h1>{t("syndication.admin.title")}</h1><p>{t("syndication.admin.subtitle")}</p></div><Link className="dashboard-action" href={`/feed.xml?locale=${locale}`} target="_blank">{t("syndication.admin.viewFeed")}</Link></header>
    <div className="dashboard-grid syndication-metrics"><section className="dashboard-card metric"><strong>{feeds.length}</strong><span>{t("syndication.admin.sources")}</span></section><section className="dashboard-card metric"><strong>{latestItems.length}</strong><span>{t("syndication.admin.recentItems")}</span></section><section className="dashboard-card metric"><strong>{failureTotal}</strong><span>{t("syndication.admin.failedDeliveries")}</span></section></div>
    <div className="dashboard-row syndication-forms"><section className="dashboard-card"><h2>{t("syndication.admin.addSource")}</h2><form className="dashboard-form" action={createFeedSubscription}><label>{t("syndication.admin.sourceName")}<input name="title" maxLength={120} placeholder={t("syndication.admin.sourcePlaceholder")} required /></label><label>{t("syndication.admin.feedUrl")}<input name="url" type="url" placeholder="https://example.com/feed.xml" required /></label><small>{t("syndication.admin.feedHint")}</small><button>{t("syndication.admin.addSourceAction")}</button></form></section><section className="dashboard-card"><h2>{t("syndication.admin.addTarget")}</h2><form className="dashboard-form" action={createDeliveryTarget}><label>{t("syndication.admin.targetName")}<input name="name" maxLength={80} placeholder={t("syndication.admin.targetPlaceholder")} required /></label><label>{t("syndication.admin.channelType")}<select name="channel" defaultValue="webhook"><option value="webhook">{t("channel.webhook")}</option><option value="newsletter">{t("channel.newsletter")}</option><option value="social">{t("channel.social")}</option></select></label><label>{t("syndication.admin.endpoint")}<input name="endpoint" type="url" placeholder="https://hooks.example.com/picoo" required /></label><small>{t("syndication.admin.targetHint")}</small><button>{t("syndication.admin.saveTarget")}</button></form></section></div>
    <section className="dashboard-card syndication-section"><h2>{t("syndication.admin.sources")}</h2><div className="setting-list">{feeds.map((feed) => <article className="setting-item syndication-source" key={feed.id}><div><b>{feed.title} <span className={`status-badge ${feed.status}`}>{t(FEED_STATUS_MESSAGES[feed.status])}</span></b><small>{feed.url}</small><small>{Number(feed.itemCount)} {t("common.items")} · {t("syndication.admin.lastSuccess")}: {displayTime(feed.lastSuccessfulAt)} · {t("syndication.admin.failures")}: {feed.failureCount}</small>{feed.lastError && <small className="syndication-error">{feed.lastError}</small>}</div><div className="review-actions"><form action={pollFeedSubscription}><input type="hidden" name="id" value={feed.id} /><button className="approve">{t("syndication.admin.pollNow")}</button></form><form action={toggleFeedSubscription}><input type="hidden" name="id" value={feed.id} /><input type="hidden" name="status" value={feed.status} /><button>{t("syndication.admin.toggle")}</button></form><form action={deleteFeedSubscription}><input type="hidden" name="id" value={feed.id} /><button>{t("common.delete")}</button></form></div></article>)}{feeds.length === 0 && <p>{t("syndication.admin.emptySources")}</p>}</div></section>
    <section className="dashboard-card syndication-section"><h2>{t("syndication.admin.targets")}</h2><div className="setting-list">{targets.map((target) => { let stateLabel = t("common.disabled"); if (target.enabled) stateLabel = t("common.enabled"); return <article className="setting-item" key={target.id}><div><b>{target.name} <span className="role-badge">{t(DELIVERY_CHANNEL_MESSAGES[target.channel])}</span></b><small>{target.endpoint}</small></div><form action={toggleDeliveryTarget}><input type="hidden" name="id" value={target.id} /><input type="hidden" name="enabled" value={String(target.enabled)} /><button>{stateLabel}</button></form></article>; })}{targets.length === 0 && <p>{t("syndication.admin.emptyTargets")}</p>}</div></section>
    <section className="dashboard-card syndication-section"><h2>{t("syndication.admin.recent")}</h2><table className="dashboard-table"><thead><tr><th>{t("syndication.admin.column.title")}</th><th>{t("syndication.admin.column.source")}</th><th>{t("syndication.admin.column.published")}</th></tr></thead><tbody>{latestItems.map((item) => <tr key={item.id}><td><a href={item.canonicalUrl} target="_blank" rel="noreferrer">{item.title}</a></td><td>{item.sourceTitle}</td><td>{displayTime(item.publishedAt)}</td></tr>)}</tbody></table>{latestItems.length === 0 && <p>{t("syndication.admin.emptyRecent")}</p>}</section>
  </>;
}
